// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package notificationdb

import (
	"time"
)

type Notification struct {
	ID        string
	UserID    string
	Title     string
	Message   string
	IsRead    int64
	CreatedAt time.Time
}
