// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package notificationdb

import (
	"context"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, user_id, title, message, created_at)
VALUES (?, ?, ?, ?, datetime('now'))
`

type CreateNotificationParams struct {
	ID      string
	UserID  string
	Title   string
	Message string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Message,
	)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, title, message, is_read, created_at
FROM notifications
WHERE id = ?
`

func (q *Queries) GetNotificationByID(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT id, user_id, title, message, is_read, created_at
FROM notifications
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListNotificationsByUserID(ctx context.Context, userID string) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, title, message, is_read, created_at
FROM notifications
WHERE user_id = ? AND is_read = 0
ORDER BY created_at DESC
`

func (q *Queries) ListUnreadNotifications(ctx context.Context, userID string) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notifications
SET is_read = 1
WHERE user_id = ? AND is_read = 0
`

func (q *Queries) MarkAllAsRead(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, markAllAsRead, userID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notifications
SET is_read = 1
WHERE id = ?
`

func (q *Queries) MarkAsRead(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markAsRead, id)
	return err
}
