// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package albumdb

import (
	"time"
)

type Album struct {
	ID          string
	UserID      string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AlbumMedium struct {
	AlbumID string
	MediaID string
	AddedAt time.Time
}
