// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package albumdb

import (
	"context"
)

const addMediaToAlbum = `-- name: AddMediaToAlbum :exec
INSERT INTO album_media (album_id, media_id, added_at)
VALUES (?, ?, datetime('now'))
`

type AddMediaToAlbumParams struct {
	AlbumID string
	MediaID string
}

func (q *Queries) AddMediaToAlbum(ctx context.Context, arg AddMediaToAlbumParams) error {
	_, err := q.db.ExecContext(ctx, addMediaToAlbum, arg.AlbumID, arg.MediaID)
	return err
}

const createAlbum = `-- name: CreateAlbum :exec
INSERT INTO albums (id, user_id, name, description, created_at, updated_at)
VALUES (?, ?, ?, ?, datetime('now'), datetime('now'))
`

type CreateAlbumParams struct {
	ID          string
	UserID      string
	Name        string
	Description string
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, createAlbum,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
	)
	return err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums
WHERE id = ?
`

func (q *Queries) DeleteAlbum(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAlbum, id)
	return err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, user_id, name, description, created_at, updated_at
FROM albums
WHERE id = ?
`

func (q *Queries) GetAlbumByID(ctx context.Context, id string) (Album, error) {
	row := q.db.QueryRowContext(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultAlbumByUserID = `-- name: GetDefaultAlbumByUserID :one
SELECT id, user_id, name, description, created_at, updated_at
FROM albums
WHERE user_id = ? AND name = 'All Media'
`

func (q *Queries) GetDefaultAlbumByUserID(ctx context.Context, userID string) (Album, error) {
	row := q.db.QueryRowContext(ctx, getDefaultAlbumByUserID, userID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlbumsByMediaID = `-- name: ListAlbumsByMediaID :many
SELECT a.id, a.user_id, a.name, a.description, a.created_at, a.updated_at
FROM albums a
JOIN album_media am ON a.id = am.album_id
WHERE am.media_id = ?
ORDER BY a.created_at DESC
`

func (q *Queries) ListAlbumsByMediaID(ctx context.Context, mediaID string) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByUserID = `-- name: ListAlbumsByUserID :many
SELECT id, user_id, name, description, created_at, updated_at
FROM albums
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAlbumsByUserID(ctx context.Context, userID string) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaInAlbum = `-- name: ListMediaInAlbum :many
SELECT album_id, media_id, added_at
FROM album_media
WHERE album_id = ?
ORDER BY added_at DESC
`

func (q *Queries) ListMediaInAlbum(ctx context.Context, albumID string) ([]AlbumMedium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaInAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumMedium
	for rows.Next() {
		var i AlbumMedium
		if err := rows.Scan(&i.AlbumID, &i.MediaID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMediaFromAlbum = `-- name: RemoveMediaFromAlbum :exec
DELETE FROM album_media
WHERE album_id = ? AND media_id = ?
`

type RemoveMediaFromAlbumParams struct {
	AlbumID string
	MediaID string
}

func (q *Queries) RemoveMediaFromAlbum(ctx context.Context, arg RemoveMediaFromAlbumParams) error {
	_, err := q.db.ExecContext(ctx, removeMediaFromAlbum, arg.AlbumID, arg.MediaID)
	return err
}

const updateAlbum = `-- name: UpdateAlbum :exec
UPDATE albums
SET name = ?, description = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateAlbumParams struct {
	Name        string
	Description string
	ID          string
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, updateAlbum, arg.Name, arg.Description, arg.ID)
	return err
}
