// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mediadb

import (
	"database/sql"
	"time"
)

type MediaReadModel struct {
	ID               string
	UserID           string
	Filename         string
	ContentType      string
	Size             int64
	StoragePath      string
	ThumbnailPath    sql.NullString
	Width            sql.NullInt64
	Height           sql.NullInt64
	DurationSeconds  sql.NullFloat64
	Status           string
	LastEventVersion int64
	UploadedAt       time.Time
	UpdatedAt        time.Time
}

type ProjectorOffset struct {
	ID            string
	LastTimestamp time.Time
	UpdatedAt     time.Time
}
