// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sagadb

import (
	"database/sql"
	"time"
)

type ProjectorOffset struct {
	ID            string
	LastTimestamp time.Time
	UpdatedAt     time.Time
}

type Saga struct {
	ID          string
	SagaType    string
	CurrentStep string
	Status      string
	Payload     string
	StartedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt sql.NullTime
}

type SagaStep struct {
	ID          string
	SagaID      string
	StepName    string
	Status      string
	Result      string
	StartedAt   sql.NullTime
	CompletedAt sql.NullTime
	RetryCount  int64
	LastError   string
}
