// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gatewaydb

import (
	"time"
)

type User struct {
	ID             string
	Provider       string
	ProviderUserID string
	Email          string
	DisplayName    string
	AvatarUrl      string
	CreatedAt      time.Time
	LastLoginAt    time.Time
}
