// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package gatewaydb

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, provider, provider_user_id, email, display_name, avatar_url, created_at, last_login_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type CreateUserParams struct {
	ID             string
	Provider       string
	ProviderUserID string
	Email          string
	DisplayName    string
	AvatarUrl      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, provider, provider_user_id, email, display_name, avatar_url, created_at, last_login_at
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, provider, provider_user_id, email, display_name, avatar_url, created_at, last_login_at
FROM users
WHERE provider = ? AND provider_user_id = ?
`

type GetUserByProviderParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProvider, arg.Provider, arg.ProviderUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = datetime('now')
WHERE id = ?
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET display_name = ?, avatar_url = ?, last_login_at = datetime('now')
WHERE id = ?
`

type UpdateUserProfileParams struct {
	DisplayName string
	AvatarUrl   string
	ID          string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile, arg.DisplayName, arg.AvatarUrl, arg.ID)
	return err
}
