// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package eventstoredb

import (
	"time"
)

type Event struct {
	ID            string
	AggregateID   string
	AggregateType string
	EventType     string
	Data          string
	Version       int64
	CreatedAt     time.Time
}
