// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package eventstoredb

import (
	"context"
	"time"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (id, aggregate_id, aggregate_type, event_type, data, version, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AppendEventParams struct {
	ID            string
	AggregateID   string
	AggregateType string
	EventType     string
	Data          string
	Version       int64
	CreatedAt     time.Time
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Data,
		arg.Version,
		arg.CreatedAt,
	)
	return err
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, aggregate_id, aggregate_type, event_type, data, version, created_at
FROM events
ORDER BY created_at ASC
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Data,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByAggregateID = `-- name: GetEventsByAggregateID :many
SELECT id, aggregate_id, aggregate_type, event_type, data, version, created_at
FROM events
WHERE aggregate_id = ?
ORDER BY version ASC
`

func (q *Queries) GetEventsByAggregateID(ctx context.Context, aggregateID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByAggregateID, aggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Data,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByAggregateType = `-- name: GetEventsByAggregateType :many
SELECT id, aggregate_id, aggregate_type, event_type, data, version, created_at
FROM events
WHERE aggregate_type = ?
ORDER BY created_at ASC
`

func (q *Queries) GetEventsByAggregateType(ctx context.Context, aggregateType string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByAggregateType, aggregateType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Data,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByType = `-- name: GetEventsByType :many
SELECT id, aggregate_id, aggregate_type, event_type, data, version, created_at
FROM events
WHERE event_type = ?
ORDER BY created_at ASC
`

func (q *Queries) GetEventsByType(ctx context.Context, eventType string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByType, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Data,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsSince = `-- name: GetEventsSince :many
SELECT id, aggregate_id, aggregate_type, event_type, data, version, created_at
FROM events
WHERE created_at > ?
ORDER BY created_at ASC
`

func (q *Queries) GetEventsSince(ctx context.Context, createdAt time.Time) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Data,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestVersion = `-- name: GetLatestVersion :one
SELECT COALESCE(MAX(version), 0) AS latest_version
FROM events
WHERE aggregate_id = ?
`

func (q *Queries) GetLatestVersion(ctx context.Context, aggregateID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersion, aggregateID)
	var latest_version interface{}
	err := row.Scan(&latest_version)
	return latest_version, err
}
